ALTER TABLE `character_queststatus` 
MODIFY COLUMN `status` TINYINT UNSIGNED NOT NULL,

MODIFY COLUMN `mobcount1` SMALLINT UNSIGNED NOT NULL,
MODIFY COLUMN `mobcount2` SMALLINT UNSIGNED NOT NULL AFTER `mobcount1`,
MODIFY COLUMN `mobcount3` SMALLINT UNSIGNED NOT NULL AFTER `mobcount2`,
MODIFY COLUMN `mobcount4` SMALLINT UNSIGNED NOT NULL AFTER `mobcount3`,

MODIFY COLUMN `itemcount1` SMALLINT UNSIGNED NOT NULL,
MODIFY COLUMN `itemcount2` SMALLINT UNSIGNED NOT NULL AFTER `itemcount1`,
MODIFY COLUMN `itemcount3` SMALLINT UNSIGNED NOT NULL AFTER `itemcount2`,
MODIFY COLUMN `itemcount4` SMALLINT UNSIGNED NOT NULL AFTER `itemcount3`,
MODIFY COLUMN `itemcount5` SMALLINT UNSIGNED NOT NULL AFTER `itemcount4`,
MODIFY COLUMN `itemcount6` SMALLINT UNSIGNED NOT NULL AFTER `itemcount5`,

MODIFY COLUMN `timer`  int(4) UNSIGNED NOT NULL AFTER `explored`;