CREATE TABLE `queuedGifts` (
  `qIdx` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `charGuid` INT UNSIGNED NOT NULL,
  `itemId` INT UNSIGNED NOT NULL,
  `itemStackCnt` INT UNSIGNED DEFAULT 1,
  `itemGuid` INT UNSIGNED NOT NULL,
  `sentFlag` INT UNSIGNED DEFAULT 0,
  PRIMARY KEY (`qIdx`)
)
ENGINE = MyISAM;

